### ISSUE TITLE
goalは名詞

### ISSUE THREAD

**Issue by faithandbrave** [ssa-study/AStarPathfinding#1]
https://github.com/ssa-study/AStarPathfinding/blob/fc24bce/AStarPathfinding/Assets/PathFinding2D/Scripts/AStarPathfindLogic.cs#L118

goaledという関数名が使われていますが、goalは動詞ではなく名詞であるため、過去形はありません。
命名規則をPascalCaseにすることも合わせて、`FoundGoal`とかにするのがよいと思います。

**Comment by h-godai** [comment]
startとgoalをセットで使うのがよくないですね。start - finish にします。
